# Generated by Django 2.1.5 on 2019-02-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190202_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gantt',
            name='fascia_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('pan', 'Pintura'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('fas', 'Fascia'), ('spr', 'Spreader')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='fundation_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('pan', 'Pintura'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('fas', 'Fascia'), ('spr', 'Spreader')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='lifting_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('pan', 'Pintura'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('fas', 'Fascia'), ('spr', 'Spreader')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='paint_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('pan', 'Pintura'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('fas', 'Fascia'), ('spr', 'Spreader')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='signage_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('pan', 'Pintura'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('fas', 'Fascia'), ('spr', 'Spreader')], default='', max_length=20),
        ),
    ]
