# Generated by Django 2.1.5 on 2019-02-03 00:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190202_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='gantt',
            name='fascia_parent',
            field=models.CharField(choices=[(' ', 'Sin prescedencia'), ('lif', 'Izaje'), ('sig', 'Rótulos'), ('spr', 'Spreader'), ('fas', 'Fascia'), ('pan', 'Pintura'), ('fun', 'Cimentación')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='fundation_parent',
            field=models.CharField(choices=[(' ', 'Sin prescedencia'), ('lif', 'Izaje'), ('sig', 'Rótulos'), ('spr', 'Spreader'), ('fas', 'Fascia'), ('pan', 'Pintura'), ('fun', 'Cimentación')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='lifting_parent',
            field=models.CharField(choices=[(' ', 'Sin prescedencia'), ('lif', 'Izaje'), ('sig', 'Rótulos'), ('spr', 'Spreader'), ('fas', 'Fascia'), ('pan', 'Pintura'), ('fun', 'Cimentación')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='paint_parent',
            field=models.CharField(choices=[(' ', 'Sin prescedencia'), ('lif', 'Izaje'), ('sig', 'Rótulos'), ('spr', 'Spreader'), ('fas', 'Fascia'), ('pan', 'Pintura'), ('fun', 'Cimentación')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='signage_parent',
            field=models.CharField(choices=[(' ', 'Sin prescedencia'), ('lif', 'Izaje'), ('sig', 'Rótulos'), ('spr', 'Spreader'), ('fas', 'Fascia'), ('pan', 'Pintura'), ('fun', 'Cimentación')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='spreader_parent',
            field=models.CharField(choices=[(' ', 'Sin prescedencia'), ('lif', 'Izaje'), ('sig', 'Rótulos'), ('spr', 'Spreader'), ('fas', 'Fascia'), ('pan', 'Pintura'), ('fun', 'Cimentación')], default='', max_length=20),
        ),
    ]
