# Generated by Django 2.1.5 on 2019-02-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190203_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gantt',
            name='fascia_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('fas', 'Fascia')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='fundation_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('fas', 'Fascia')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='lifting_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('fas', 'Fascia')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='paint_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('fas', 'Fascia')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='signage_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('fas', 'Fascia')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='spreader_parent',
            field=models.CharField(choices=[('lif', 'Izaje'), ('spr', 'Spreader'), ('pan', 'Pintura'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('fas', 'Fascia')], default='', max_length=20),
        ),
    ]
