# Generated by Django 2.1.5 on 2019-02-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190203_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gantt',
            name='fascia_parent',
            field=models.CharField(choices=[('pan', 'Pintura'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('spr', 'Spreader'), ('lif', 'Izaje'), ('sig', 'Rótulos')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='fundation_parent',
            field=models.CharField(choices=[('pan', 'Pintura'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('spr', 'Spreader'), ('lif', 'Izaje'), ('sig', 'Rótulos')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='lifting_parent',
            field=models.CharField(choices=[('pan', 'Pintura'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('spr', 'Spreader'), ('lif', 'Izaje'), ('sig', 'Rótulos')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='paint_parent',
            field=models.CharField(choices=[('pan', 'Pintura'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('spr', 'Spreader'), ('lif', 'Izaje'), ('sig', 'Rótulos')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='signage_parent',
            field=models.CharField(choices=[('pan', 'Pintura'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('spr', 'Spreader'), ('lif', 'Izaje'), ('sig', 'Rótulos')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='spreader_parent',
            field=models.CharField(choices=[('pan', 'Pintura'), ('fas', 'Fascia'), (' ', 'Sin prescedencia'), ('fun', 'Cimentación'), ('spr', 'Spreader'), ('lif', 'Izaje'), ('sig', 'Rótulos')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo_1',
            field=models.ImageField(upload_to='photos/projects/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo_2',
            field=models.ImageField(upload_to='photos/projects/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo_3',
            field=models.ImageField(upload_to='photos/projects/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo_4',
            field=models.ImageField(upload_to='photos/projects/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo_5',
            field=models.ImageField(upload_to='photos/projects/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo_6',
            field=models.ImageField(upload_to='photos/projects/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo_main',
            field=models.ImageField(upload_to='photos/projects/%Y/%m'),
        ),
    ]
