# Generated by Django 2.1.5 on 2019-02-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190203_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gantt',
            name='fascia_parent',
            field=models.CharField(choices=[('fas', 'Fascia'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('sig', 'Rótulos'), ('spr', 'Spreader'), (' ', 'Sin prescedencia'), ('lif', 'Izaje')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='fundation_parent',
            field=models.CharField(choices=[('fas', 'Fascia'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('sig', 'Rótulos'), ('spr', 'Spreader'), (' ', 'Sin prescedencia'), ('lif', 'Izaje')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='lifting_parent',
            field=models.CharField(choices=[('fas', 'Fascia'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('sig', 'Rótulos'), ('spr', 'Spreader'), (' ', 'Sin prescedencia'), ('lif', 'Izaje')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='paint_parent',
            field=models.CharField(choices=[('fas', 'Fascia'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('sig', 'Rótulos'), ('spr', 'Spreader'), (' ', 'Sin prescedencia'), ('lif', 'Izaje')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='signage_parent',
            field=models.CharField(choices=[('fas', 'Fascia'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('sig', 'Rótulos'), ('spr', 'Spreader'), (' ', 'Sin prescedencia'), ('lif', 'Izaje')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='spreader_parent',
            field=models.CharField(choices=[('fas', 'Fascia'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('sig', 'Rótulos'), ('spr', 'Spreader'), (' ', 'Sin prescedencia'), ('lif', 'Izaje')], default='', max_length=20),
        ),
    ]
