# Generated by Django 2.1.5 on 2019-02-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20190203_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-project']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-project']},
        ),
        migrations.AlterField(
            model_name='gantt',
            name='fascia_parent',
            field=models.CharField(choices=[('spr', 'Spreader'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('lif', 'Izaje'), ('fas', 'Fascia'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='fundation_parent',
            field=models.CharField(choices=[('spr', 'Spreader'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('lif', 'Izaje'), ('fas', 'Fascia'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='lifting_parent',
            field=models.CharField(choices=[('spr', 'Spreader'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('lif', 'Izaje'), ('fas', 'Fascia'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='paint_parent',
            field=models.CharField(choices=[('spr', 'Spreader'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('lif', 'Izaje'), ('fas', 'Fascia'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='signage_parent',
            field=models.CharField(choices=[('spr', 'Spreader'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('lif', 'Izaje'), ('fas', 'Fascia'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='spreader_parent',
            field=models.CharField(choices=[('spr', 'Spreader'), ('pan', 'Pintura'), ('fun', 'Cimentación'), ('lif', 'Izaje'), ('fas', 'Fascia'), ('sig', 'Rótulos'), (' ', 'Sin prescedencia')], default='', max_length=20),
        ),
    ]
